name: fly.io deploy
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_IMAGE: registry.fly.io/ktor-github-package-registry-proxy:${{ github.sha }}
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Fly.io tools
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Auth to Fly.io
        run: flyctl auth docker
      - name: Push to Fly.io docker registry
        run: ./gradlew jib --image=$APP_IMAGE
      - name: Deploy app
        run: flyctl deploy -i $APP_IMAGE
